service: es-lambda-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  role: arn:aws:iam::760423090131:role/dashboard-role
  vpc:
    securityGroupIds:
      - sg-0d21e9bff0506a3cb
    subnetIds:
      - subnet-0e4485c28228684d6
      - subnet-06269aa8c5403ecd3 

functions:
  es:
    handler: handler.es

